# Generated by Django 4.0.6 on 2022-07-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_link'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
