# Generated by Django 4.0.6 on 2022-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='random',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
